### ISSUE TITLE
Issue Building Latest Release

### ISSUE THREAD

**Issue by james-crowley** [a10networks/terraform-provider-thunder#25]
When building the latest release of `v0.4.6` there is an error the prevents the user from compiling the binary. The error I am seeing is:

```
go: downloading github.com/hashicorp/golang-lru v0.5.1
Main.go:5:2: package terraform-provider-vthunder/vthunder is not in GOROOT (/usr/local/go/src/terraform-provider-vthunder/vthunder)
```

From my understanding in your `Main.go` file you should have the path of:

```
"github.com/terraform-providers/terraform-provider-vthunder/vthunder"
```

Not the current path of `"terraform-provider-vthunder/vthunder"`. It looks like this error was fixed by @cgriggs01 in the last release you have upstream with Terraform. Here is the commit, https://github.com/hashicorp/terraform-provider-vthunder/commit/0087669bf83f1adacd07d2e74762f7568a2410e3.
 

@devendra-bhatt-a10 @asharma-a10 Do you guys plan on fixing these errors and pushing a new release upstream with Terraform in the near future?

**Comment by devendra-bhatt-a10** [comment]
Yes @james-crowley, I'll have a look into it right away. Though I'm able to build it locally. You can also find the builds as zip in the tags section for time being.

**Comment by james-crowley** [comment]
@devendra-bhatt-a10 I am pulling from your releases. I am downloading the tar.gz which has the problem. Your releases(zip and tar) should be the the same as your tags.

I tried both cloning and downloading the releases, both fail. The build commands are I use are:

```
a10networks-terraform-provider-vthunder-v0.4.6.tar.gz was successfully extracted to /go/src/github.com/a10networks/terraform-provider-vthunder/

cd /go/src/github.com/a10networks/terraform-provider-vthunder/

go build -ldflags '-d -s -w'
```

**Comment by devendra-bhatt-a10** [comment]
Hi @james-crowley, 

That is one way to do but it requires all the dependencies in place to build locally.
We use the following build command - "go build -o terraform-provider-thunder"

Instead, I would recomand you to download pre-built binary from this souce - https://github.com/a10networks/terraform-provider-thunder/releases/tag/v0.4.14
In this link you will find OS specefic zip files. You simply need to unzip it and place it with your TF scripts.
Eg, terraform-provider-thunder_0.4.14_linux_amd64.zip

If you are still stuck then please let me know.

**Comment by james-crowley** [comment]
@devendra-bhatt-a10 I'll give you command a go, but that is going against what the majority of Terraform providers are doing.  Which makes this provider an outlier.

> Instead, I would recomand you to download pre-built binary from this souce - https://github.com/a10networks/terraform-provider-thunder/releases/tag/v0.4.14
In this link you will find OS specefic zip files. You simply need to unzip it and place it with your TF scripts.
Eg, terraform-provider-thunder_0.4.14_linux_amd64.zip

The reason I am building the provider manually is to get it running on `ppc64le` and `s390x`. Hence using your precompiled binaries for `amd64` will not work. If you can to start cross-compiling your binaries for other architectures that would be great!

**Comment by devendra-bhatt-a10** [comment]
Okay, we will start publishing "linux/s390x" and "linux/ppc64le" from the next release. Please let me know if you require some other build as well so we can start publishing them from our next release as well.

**Comment by devendra-bhatt-a10** [comment]
Okay, we will start publishing "linux/s390x" and "linux/ppc64le" from the next release. Please let me know if you require some other build as well so we can start publishing them from our next release as well.
